name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Build
        env:
          AVN_GPG_PASSWORD: ${{ secrets.AVN_GPG_PASSWORD }}
          AVN_KEYSTORE_PASSWORD: ${{ secrets.AVN_KEYSTORE_PASSWORD }}
          AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
          AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase=$AVN_GPG_PASSWORD --output .github/avereon.keystore .github/avereon.keystore.gpg
          mvn deploy -B -U -V --settings .github/settings.xml --file pom.xml
